import {Quote} from "../models/Quote";

export const quotes:Quote[] = [
  {
    id:0,
    language:'tr',
    text:"Konuşmak ihtiyaç olabilir ama susmak bir sanattır.",
    author:"goethe",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    id:1,
    language:'tr',
    text:"Yüz çeşit şeyi yarım bilmektense bir şeyi tam bilip uygulamak insanı daha iyi yetiştirir",
    author:"goethe",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    id:2,
    language:'tr',
    text:"Sanattan anlamayan sanat eserini, sanat eserini bilmeyen de sanatkarı bilemez",
    author:"ibn rüşd",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    id:3,
    language:'tr',
    text:"Dostun verdiği eziyet düşmanın verdiği eziyetten daha acıdır.",
    author:"ibn rüşd",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    id:4,
    language:'tr',
    text:"Cesaret, devam etmeye gücünün olması değildir; gücün olmadığında devam edebilmektir",
    author:"Napoleon Bonaparte",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    id:5,
    language:'tr',
    text:"Kuru duayı bırak, ağaç isteyen tohum eker",
    author:"mevlana",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    id:6,
    language:'tr',
    text:"Dışa bakan rüya gçrür, içe bakan uyanır",
    author:"Carl Gustav Jung",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    text:"Fiziksel olarak acı çekmesem de, ruhsal olarak sonsuz acılara katlanıyorum",
    author:"Edgar Allen Poe",
    id:7,
    language:'tr',
    source:"Kara Kedi",
    categories:[],
    likes:24,
  },
  {
    text:"Çiğ tanesi sanmak ne cüret, gözyaşıymış insanın insana raptolduğu cevher...",
    author:"İsmet Özel",
    id:8,
    language:'tr',
    categories:["poem"],
    source:"",
    likes:24,
  },
  {
    id:9,
    language:'tr',
    text:"        ",
    author:"",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    id:10,
    language:'tr',
    text:"Benim içimde, daima var olacağını zannettiğim birçok şey yok oldu",
    author:"marcel proust",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    id:11,
    language:'tr',
    text:"Aradığın seni arayandır",
    author:"mevlana",
    source:"books",
    categories:[],
    likes:24,
  },
  {
    text:"“Sen çok kıymetli bir inciyi aradıkça o inci olursun, sen ekmek peşinde koşar, sadece ekmek düşünürsen ekmek kesilirsin. Sen bu nükteli ve rumuzlu sözü anlarsan her şeye aklın erer: Ne arıyorsan, neyin arkasından koşuyorsan , sen osun, o şeysin.”",
    source:"books",
    id:12,
    language:'tr',
    author:"anonim",
    categories:[],
    likes:24,
  },
  {
    id:13,
    language:'tr',
    text:"        ",
    author:"",
    source:"books",
    categories:[],
    likes:24,
  },


]
