import {Quote} from "../models/Quote";

export const quotes:Quote[] = [
  {
    id:0,
    language:'tr',
    text:"Konuşmak ihtiyaç olabilir ama susmak bir sanattır",
    author:"goethe",
    source:"books",
    categories:[],
    likes:36,
  },
  {
    id:1,
    language:'tr',
    text:"Yüz çeşit şeyi yarım bilmektense bir şeyi tam bilip uygulamak insanı daha iyi yetiştirir",
    author:"goethe",
    source:"books",
    categories:[],
    likes:1234,
  },
  {
    id:2,
    language:'tr',
    text:"Sanattan anlamayan sanat eserini, sanat eserini bilmeyen de sanatkarı bilemez",
    author:"ibn rüşd",
    source:"books",
    categories:[],
    likes:71,
  },
  {
    id:3,
    language:'tr',
    text:"Dostun verdiği eziyet düşmanın verdiği eziyetten daha acıdır",
    author:"ibn rüşd",
    source:"books",
    categories:[],
    likes:82,
  },
  {
    id:4,
    language:'tr',
    text:"Cesaret, devam etmeye gücünün olması değildir; gücün olmadığında devam edebilmektir",
    author:"Napoleon Bonaparte",
    source:"books",
    categories:[],
    likes:5,
  },
  {
    id:5,
    language:'tr',
    text:"sa beyler turk warmi?",
    author:"MEMED",
    source:"books",
    categories:[],
    likes:84565,
  },
  {
    id:6,
    language:'tr',
    text:"Dışa bakan rüya görür, içe bakan uyanır",
    author:"Carl Gustav Jung",
    source:"books",
    categories:[],
    likes:9243,
  },
  {
    text:"Fiziksel olarak acı çekmesem de, ruhsal olarak sonsuz acılara katlanıyorum",
    author:"Edgar Allen Poe",
    id:7,
    language:'tr',
    source:"Kara Kedi",
    categories:[],
    likes:62,
  },
  {
    text:"Çiğ tanesi sanmak ne cüret, gözyaşıymış insanın insana raptolduğu cevher",
    author:"İsmet Özel",
    id:8,
    language:'tr',
    categories:["poem"],
    source:"",
    likes:71,
  },
  {
    id:9,
    language:'tr',
    text:"Kuru duayı bırak, ağaç isteyen tohum eker",
    author:"mevlana",
    source:"books",
    categories:[],
    likes:75,
  },
  {
    id:10,
    language:'tr',
    text:"Benim içimde, daima var olacağını zannettiğim birçok şey yok oldu",
    author:"marcel proust",
    source:"books",
    categories:[],
    likes:354,
  },
  {
    id:11,
    language:'tr',
    text:"Aradığın seni arayandır",
    author:"mevlana",
    source:"books",
    categories:[],
    likes:741,
  },
  {
    text:"Sen çok kıymetli bir inciyi aradıkça o inci olursun, sen ekmek peşinde koşar, sadece ekmek düşünürsen ekmek kesilirsin. Sen bu nükteli ve rumuzlu sözü anlarsan her şeye aklın erer: Ne arıyorsan, neyin arkasından koşuyorsan , sen osun, o şeysin",
    source:"books",
    id:12,
    language:'tr',
    author:"anonim",
    categories:[],
    likes:571,
  },
  {
    id:13,
    language:'en',
    text:"Nothing makes a man so adventurous as an empty pocket",
    author:"Victor hugo",
    source:"books",
    categories:[],
    likes:9999,
  },
  {
    id:14,
    language:'tr',
    text:"Medyanın gücü yoktur, gücün medyası vardır",
    author:"Victor hugo",
    source:"books",
    categories:[],
    likes:9999,
  },


]
