import { Quote } from "../models/Quote";

export const quotes: Quote[] = [
  {
    id: 0,
    language: 'tr',
    text: "Konuşmak ihtiyaç olabilir ama susmak bir sanattır",
    author: "goethe",
    source: "",
    categories: [],
    likes: 36,
  },
  {
    id: 1,
    language: 'tr',
    text: "Yüz çeşit şeyi yarım bilmektense bir şeyi tam bilip uygulamak insanı daha iyi yetiştirir",
    author: "goethe",
    source: "",
    categories: ["knowledge"],
    likes: 1234,
  },
  {
    id: 2,
    language: 'tr',
    text: "Sanattan anlamayan sanat eserini, sanat eserini bilmeyen de sanatkarı bilemez",
    author: "ibn rüşd",
    source: "",
    categories: ["art", "religion"],
    likes: 71,
  },
  {
    id: 3,
    language: 'tr',
    text: "Dostun verdiği eziyet düşmanın verdiği eziyetten daha acıdır",
    author: "ibn rüşd",
    source: "",
    categories: [],
    likes: 82,
  },
  {
    id: 4,
    language: 'tr',
    text: "Cesaret, devam etmeye gücünün olması değildir; gücün olmadığında devam edebilmektir",
    author: "Napoleon Bonaparte",
    source: "",
    categories: [],
    likes: 5,
  },
  {
    id: 5,
    language: 'tr',
    text: "sa beyler turk warmi?",
    author: "MEMED",
    source: "",
    categories: [],
    likes: 84565,
  },
  {
    id: 6,
    language: 'tr',
    text: "Dışa bakan rüya görür, içe bakan uyanır",
    author: "Carl Gustav Jung",
    source: "",
    categories: [],
    likes: 9243,
  },
  {
    text: "Fiziksel olarak acı çekmesem de, ruhsal olarak sonsuz acılara katlanıyorum",
    author: "Edgar Allen Poe",
    id: 7,
    language: 'tr',
    source: "Kara Kedi",
    categories: [],
    likes: 62,
  },
  {
    text: "Çiğ tanesi sanmak ne cüret, gözyaşıymış insanın insana raptolduğu cevher",
    author: "İsmet Özel",
    id: 8,
    language: 'tr',
    categories: ["poem"],
    source: "",
    likes: 71,
  },
  {
    id: 9,
    language: 'tr',
    text: "Kuru duayı bırak, ağaç isteyen tohum eker",
    author: "mevlana",
    source: "",
    categories: [],
    likes: 75,
  },
  {
    id: 10,
    language: 'tr',
    text: "Benim içimde, daima var olacağını zannettiğim birçok şey yok oldu",
    author: "marcel proust",
    source: "",
    categories: [],
    likes: 354,
  },
  {
    id: 11,
    language: 'tr',
    text: "Aradığın seni arayandır",
    author: "mevlana",
    source: "",
    categories: [],
    likes: 741,
  },
  {
    text: "Sen çok kıymetli bir inciyi aradıkça o inci olursun, sen ekmek peşinde koşar, sadece ekmek düşünürsen ekmek kesilirsin. Sen bu nükteli ve rumuzlu sözü anlarsan her şeye aklın erer: Ne arıyorsan, neyin arkasından koşuyorsan , sen osun, o şeysin",
    source: "",
    id: 12,
    language: 'tr',
    author: "anonim",
    categories: [],
    likes: 571,
  },
  {
    id: 13,
    language: 'en',
    text: "Nothing makes a man so adventurous as an empty pocket",
    author: "Victor hugo",
    source: "",
    categories: ["life"],
    likes: 9999,
  },
  {
    id: 14,
    language: 'tr',
    text: "Medyanın gücü yoktur, gücün medyası vardır",
    author: "Victor hugo",
    source: "",
    categories: [],
    likes: 19,
  },
  {
    id: 15,
    language: 'tr',
    text: "Binlerce kez beter olsun gece, senin ışığın yoksa..",
    author: "William Shakespeare",
    source: "Romeo ve juliet",
    categories: [],
    likes: 651,
  },
  {
    id: 16,
    language: 'tr',
    text: "Gönlüm uçmak dilerken semavî ülkelere;\n" +
      "Ayağım takılıyor yerdeki gölgelere...",
    author: "Necip Fazıl Kısakürek",
    source: "Çile",
    categories: ["poem"],
    likes: 399,
  },
  {
    id: 17,
    language: 'tr',
    text: "Hepimiz hata yaparız ama önemli olan onların yerine doğruları koyabilmemizdir.",
    author: "yaşama sanatı",
    categories: ["life", "books"],
    likes: 100,
  },
  {
    id: 18,
    language: 'tr',
    text: "Çünkü insanın çekileceği en güzel yer kendi içidir",
    author: "marcus aurelius",
    source: "kendime düşünceler",
    categories: [],
    likes: 153,
  },
  {
    id: 19,
    language: 'tr',
    text: "Sabahları uyandığında hayatta olmanın, sevmenin, mutlu olmanın ve düşünmenin nasıl bir ayrıcalık olduğunu düşün.",
    author: "marcus aurelius",
    source: "kendime düşünceler",
    categories: ["life"],
    likes: 3451,
  },
  {
    id: 20,
    language: 'tr',
    text: "Ay’ın sevdiği gibi sevmek yeryüzünü ve yalnızca gözlerimle dokunmak onun güzelliğine",
    author: "friedrich nietzsche",
    source: "böyle buyurdu zerdüşt",
    categories: ["love"],
    likes: 163,
  },
  {
    id: 21,
    language: 'tr',
    text: "Biz bu dünyaya çile çekmeye ve pişmeye geldik",
    author: "kemal tahir",
    categories: ["life"],
    likes: 2113,
  },
  {
    id: 22,
    language: 'tr',
    text: "Tıngırdayan nalın bir çivisi eksiktir.",
    author: "anonim",
    source: "ispanyol atasözü",
    categories: ["proverb"],
    likes: 2713,
  },
  {
    id: 23,
    language: 'tr',
    text: "Balmumu için sıcaklık neyse insanlar için nezaket odur",
    author: "arthur schopenhauer",
    source: "yaşam bilgeliği üzerine aforizmalar, s.182, 19.basım",
    categories: ["books"],
    likes: 412,
  },
  {
    id: 24,
    language: 'tr',
    text: "Kişi insanları saçma olduğuna inandığı tüm şeylerden vazgeçirmeye çalışırsa, bunu tam olarak gerçekleştiremeden Metuşellah'ın yaşına ulaşacağını düşünmelidir",
    description: "Metuşellah: Eski Ahit'e göre, Nuh peygamberin büyükbabası, 969 yıl yaşamıştır(Tekvin,5)",
    author: "arthur schopenhauer",
    source: "yaşam bilgeliği üzerine aforizmalar, s.183, 19.basım",
    categories: ["books"],
    likes: 412,
  },
  {
    id: 25,
    language: 'tr',
    text: "İnsanlar genel gerçeklere karşı ne kadar ilgisiz ve aldırışsızsalar, bireysel gerçeklere de o kadar düşkündürler",
    author: "arthur schopenhauer",
    source: "yaşam bilgeliği üzerine aforizmalar, s.185, 19.basım",
    categories: ["books"],
    likes: 912,
  },
  {
    id: 26,
    language: 'tr',
    text: "Neyin olabileceğini düşünmek akıl, neyin olduğunu düşünmek ise sadece duyu ister",
    description: "yaşam bilgeliği üzerine aforizmalar, s.192, 19.basım",
    author: "arthur schopenhauer",
    categories: ["books"],
    likes: 6561,
  },
  {
    id: 27,
    language: 'tr',
    text: "Kibir, bele bağlanan taş gibidir. Onunla ne yüzül, ne de uçulu",
    description: "",
    author: "Hacı Bayram Veli",
    categories: [""],
    likes: 234,
  },
  {
    id: 28,
    language: 'tr',
    text: "Dünyada sanki bir garip veya bir yolcu gibi ol.",
    description: "",
    source: "Buhâri, Rikak 3",
    author: "",
    categories: ["hadith"],
    likes: 1634,
  },
  {
    id: 29,
    language: 'tr',
    text: "Sürekli iyiliğinden söz edeni, bir gün elinden çıkan bir kötülük utandırarak susturur.",
    description: "",
    author: "Muhyiddin İbnü'l Arabi",
    categories: ["people"],
    likes: 512,
  },
  {
    id: 30,
    language: 'tr',
    text: "Haksız bir davada zirve olmaktansa, haklı bir davada zerre olmayı tercih ederim",
    description: "",
    author: "Muhsin Yazıcıoğlu",
    categories: ["people"],
    likes: 3546,
  },
  {
    id: 31,
    language: 'tr',
    text: "Kasana, kesene, rütbene sarhoş olma! Üzüm sarhoşluğuna benzmez, teneşir tahtasında ayılırsın",
    description: "",
    author: "Muzaffer Özak Efendi",
    categories: [""],
    likes: 451,
  },
  {
    id: 32,
    language: 'tr',
    text: "Dergâhta akşam iki soru sorulurmuş. Bugün gönül kırdın mı? Namazını kıldın mı?" +
      "Birinci soruya evet diyene ikinci soru sorulmazmış",
    description: "",
    author: "anonim",
    categories: [""],
    likes: 8751,
  },
  {
    id: 33,
    language: 'tr',
    text: "Ölümden korkmak anlamsızdır çünkü yaşadığımız sürece ölüm yoktur, ölüm geldiğinde ise artık biz yokuz.",
    description: "",
    author: "Epikür",
    categories: ["philosophy"],
    likes: 515,
  },
  {
    id: 34,
    language: 'tr',
    text: "Yoktum, varım, olmayacağım, umrumda değil.",
    description: "",
    author: "Epikür",
    categories: ["philosophy"],
    likes: 745,
  },
  {
    id: 35,
    language: 'en',
    text: "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for",
    description: "",
    author: "Epicurus",
    categories: [""],
    likes: 1051,
  },
  {
    id: 36,
    language: 'tr',
    text: "Ölmek istemediğin yerde bulunma",
    author: "Mehmed Zahid Kotku",
    source: "people",
    categories: ["life"],
    likes: 671,
  },
  {
    id: 37,
    language: 'tr',
    text: "Sahip olduklarımızın sadece beşte biriyle idare edebilir ve değişikliğin farkına bile varmayız",
    author: "Francine Jay",
    source: "people",
    categories: ["life"],
    likes: 493,
  },
  {
    id: 38,
    language: 'tr',
    text: "Gamına gamlanıp olma mahzun, demine demlenip olma mağrur, ne dem baki ne gam baki, ya Hû",
    author: "Yavuz Sultan Selim",
    source: "people",
    categories: ["life"],
    likes: 1257,
  },
  {
    id: 39,
    language: 'tr',
    text: "Asaleti kendinden olanın gösterişe ihtiyacı yoktur. Bahçıvanın başına gül taktığı görülmemiştir...",
    author: "anonim",
    source: "",
    categories: [],
    likes: 56,
  },
  {
    id: 40,
    language: 'tr',
    text: "İlk var olan bütün diğer var olanların varlığının ilk nedenidir",
    author: "Farabi",
    source: "books",
    categories: ["philosophy"],
    likes: 716,
  },
  {
    id: 41,
    language: 'tr',
    text: "Her nereye bakarsan kendi yüzündür, kimde ne görürsen kendi özündür",
    author: "Yunus Emre",
    source: "books",
    categories: ["life"],
    likes: 854,
  },
  {
    id: 42,
    language: 'tr',
    text: "İnsan, yaratılmakla başına çok vahim bir şey geldiğini anlarsa uyanmış olur. Ölmek yaratılmış olmaktan daha şiddetli değildir.",
    author: "İsmet Özel",
    source: "",
    categories: [],
    likes: 767,
  },
  {
    id: 43,
    language: 'tr',
    text: "Sahip olduklarımız değil, keyif aldıklarımız bizim zenginliğimizi oluşturur",
    author: "Epikür",
    source: "people",
    categories: ["philosophy"],
    likes: 767,
  },
  {
    id: 44,
    language: 'tr',
    text: "Az ile yetinmeyen, hiç bir şeyle yetinmez",
    author: "Epikür",
    source: "people",
    categories: ["philosophy"],
    likes: 123,
  },
  {
    id: 45,
    language: 'tr',
    text: "Bir insanı mutlu edeceksen onun zenginliğine katma, arzularından eksilt",
    author: "Epikür",
    source: "people",
    categories: ["philosophy"],
    likes: 52,
  },
  {
    id: 46,
    language: 'tr',
    text: "Hayatınızı doğaya göre şekillendirirseniz asla fakir olmazsınız; eğer insanların görüşlerine göre şekillendirirseniz, asla zengin olamazsınız",
    author: "Epikür",
    source: "people",
    categories: ["philosophy"],
    likes: 754,
  },
  {
    id: 47,
    language: 'tr',
    text: "Edeple gelen, lütufla gider",
    author: "Aziz Mahmut Hüdai",
    source: "people",
    categories: [""],
    likes: 955,
  },



]
